var defaultOption = {
	shapeDetail: null,
	partialDraw: false,
	delayEval: true,
	fixRatio: true,
	width: null,
	height: null,
	transparent: false,
	fps: null,
	frameCallback: {},
	disableFrameSkip: false,
	cacheColoredImage : true,
	stopOnStart: false,
	enableButton: false,
	enableTouch: false,
	debug: false,
	suppressLog: {},
	origin: null,
	frameRect: null,
	compileAction: true,
	operation: {},
	cacheMaxShapeSize: null,
	cacheMaxTotalSize: null,
	onerror: null,
	enableStyleText: false,
	_enableWorkaroundForUnicolor: false,  // experimental
	colorLevels: 16,
	swfBinary: null
};
